/* ==========================================================================
   Naveen Boot House - Removed Products Archive
   This file stores the code & data for 20 archived products removed from main catalog.
   ========================================================================== */

const ARCHIVED_PRODUCTS = [
  {
    id: 101,
    title: "Crocs Swiftwater Black/White Women Flip [204974-066]",
    category: "crocs",
    categoryLabel: "Crocs Collection",
    brand: "Crocs",
    price: 1995,
    oldPrice: 2495,
    rating: 4.8,
    reviewsCount: 29,
    badge: "Archived Item",
    image: "assets/crocs_flip.png",
    description: "Classic Crocs Swiftwater black and white flip flop for women. Quick-drying, lightweight, and contoured footbed.",
    sizes: [4, 9],
    inStock: false
  },
  {
    id: 102,
    title: "Crocs Swiftwater Tropical Teal/Light Grey Women Sandal [203998-3O2]",
    category: "crocs",
    categoryLabel: "Crocs Collection",
    brand: "Crocs",
    price: 2495,
    oldPrice: 2995,
    rating: 4.9,
    reviewsCount: 41,
    badge: "Archived Item",
    image: "assets/crocs_pink.png",
    description: "Tropical teal & light grey Crocs Swiftwater sandal for women. Soft flexible straps and siped outsoles for wet traction.",
    sizes: [4, 5, 6, 7],
    inStock: false
  },
  {
    id: 103,
    title: "Crocs Capri Shimmer Xband Oyster/Cobblestone Women Sandal [204908-1C4]",
    category: "crocs",
    categoryLabel: "Crocs Collection",
    brand: "Crocs",
    price: 3495,
    oldPrice: 3995,
    rating: 4.8,
    reviewsCount: 24,
    badge: "Archived Item",
    image: "assets/crocs_pink.png",
    description: "Crocs Capri Shimmer cross-band sandal in oyster & cobblestone finish with shimmer straps and soft microfiber lining.",
    sizes: [4],
    inStock: false
  },
  {
    id: 104,
    title: "Crocs Capri Shimmer Xband Black Women Sandal [204908-060]",
    category: "crocs",
    categoryLabel: "Crocs Collection",
    brand: "Crocs",
    price: 3495,
    oldPrice: 3995,
    rating: 4.9,
    reviewsCount: 37,
    badge: "Archived Item",
    image: "assets/crocs_pink.png",
    description: "Sleek black Crocs Capri Shimmer Xband women sandal. Dual Crocs Comfort with soft massage pods on footbed.",
    sizes: [3],
    inStock: false
  },
  {
    id: 105,
    title: "Bata Power Brown Floaters for Men (F861420900)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata Power",
    price: 959,
    oldPrice: 999,
    rating: 4.8,
    reviewsCount: 91,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Rugged Bata Power brown floaters for men with shock-absorption heel cushioning and anti-slip tread pattern.",
    sizes: [6, 7, 8, 9, 10],
    inStock: false
  },
  {
    id: 106,
    title: "Bata Brown Floaters for Men (Pr-1468941)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata",
    price: 395,
    oldPrice: 450,
    rating: 4.6,
    reviewsCount: 112,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Budget-friendly durable Bata brown floaters for daily home and local town wear in Burhar.",
    sizes: [6, 7, 8, 9],
    inStock: false
  },
  {
    id: 107,
    title: "Bata Power Black Floaters for Men",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata Power",
    price: 785,
    oldPrice: 799,
    rating: 4.7,
    reviewsCount: 58,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "All-black Bata Power floaters for active men. Water-resistant synthetic material with heavy-duty soles.",
    sizes: [6, 7, 8, 9, 10],
    inStock: false
  },
  {
    id: 108,
    title: "Bata Brown Floaters for Men (Pr-1469813)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata",
    price: 671,
    oldPrice: 699,
    rating: 4.6,
    reviewsCount: 45,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Bata brown casual floaters for men with adjustable straps.",
    sizes: [7, 8, 9],
    inStock: false
  },
  {
    id: 109,
    title: "Bata Blue Floaters For Men (F861933500)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata",
    price: 379,
    oldPrice: 399,
    rating: 4.5,
    reviewsCount: 39,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Lightweight blue Bata floaters for home wear.",
    sizes: [6, 7, 8],
    inStock: false
  },
  {
    id: 110,
    title: "Bata Weinbrenner Grey Floaters for Men (F861794200)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata Weinbrenner",
    price: 1260,
    oldPrice: 1300,
    rating: 4.8,
    reviewsCount: 50,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Bata Weinbrenner grey outdoor floaters with rubber lug sole.",
    sizes: [7, 8, 9, 10],
    inStock: false
  },
  {
    id: 111,
    title: "Bata Power Grey Floaters for Men (F861283600)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata Power",
    price: 872,
    oldPrice: 899,
    rating: 4.7,
    reviewsCount: 41,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Grey active Bata Power floaters for daily use.",
    sizes: [6, 7, 8, 9],
    inStock: false
  },
  {
    id: 112,
    title: "Bata Power Grey Floaters for Men (F861738900)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata Power",
    price: 759,
    oldPrice: 799,
    rating: 4.6,
    reviewsCount: 33,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Light grey Bata Power floaters.",
    sizes: [7, 8, 9],
    inStock: false
  },
  {
    id: 113,
    title: "Bata Power Blue Floaters for Men (F861923700)",
    category: "bata",
    categoryLabel: "Bata Floaters",
    brand: "Bata Power",
    price: 845,
    oldPrice: 899,
    rating: 4.7,
    reviewsCount: 38,
    badge: "Archived Item",
    image: "assets/bata_floaters.png",
    description: "Bata Power blue floaters with quick dry straps.",
    sizes: [6, 7, 8, 9],
    inStock: false
  },
  {
    id: 114,
    title: "Nike Unisex Kid's Jr Obra 2 Club FG Football Shoes [AH7314-080]",
    category: "nike",
    categoryLabel: "Nike Sports",
    brand: "Nike Football",
    price: 3295,
    oldPrice: 3895,
    rating: 4.9,
    reviewsCount: 42,
    badge: "Archived Item",
    image: "assets/nike_flex.png",
    description: "Official Nike Jr Obra 2 Club FG Firm-Ground football cleats for kids. Synthetic leather upper with molded studs for pitch speed.",
    sizes: [3.5, 4, 5, 5.5],
    inStock: false
  },
  {
    id: 115,
    title: "Nike Varsity Compete Trainer Pure Platinum/Signal Blue",
    category: "nike",
    categoryLabel: "Nike Sports",
    brand: "Nike",
    price: 4295,
    oldPrice: 4995,
    rating: 4.8,
    reviewsCount: 36,
    badge: "Archived Item",
    image: "assets/nike_flex.png",
    description: "Ultra-lightweight 249g Nike Varsity Compete trainer in platinum and signal blue colorway.",
    sizes: [7, 8, 9, 10],
    inStock: false
  },
  {
    id: 116,
    title: "Nike Women's Lace-Up Low-Top Basketball Shoes [AQ1778]",
    category: "nike",
    categoryLabel: "Nike Sports",
    brand: "Nike Women",
    price: 4595,
    oldPrice: 5295,
    rating: 4.9,
    reviewsCount: 29,
    badge: "Archived Item",
    image: "assets/nike_flex.png",
    description: "Nike low-top basketball shoes for women with rubber cupsole traction and impact-cushioned Phylon foam midsole.",
    sizes: [5, 6, 7, 8],
    inStock: false
  },
  {
    id: 117,
    title: "Nike Men's Black Flex Control II Multisport Training Shoes",
    category: "nike",
    categoryLabel: "Nike Sports",
    brand: "Nike",
    price: 3495,
    oldPrice: 3995,
    rating: 4.7,
    reviewsCount: 40,
    badge: "Archived Item",
    image: "assets/nike_flex.png",
    description: "Multisport black Flex Control II training shoes by Nike.",
    sizes: [7, 8, 9, 10],
    inStock: false
  },
  {
    id: 118,
    title: "Nike Synthetic Blue & Metallic Silver Flex Control II Training Shoes",
    category: "nike",
    categoryLabel: "Nike Sports",
    brand: "Nike",
    price: 3695,
    oldPrice: 4195,
    rating: 4.8,
    reviewsCount: 31,
    badge: "Archived Item",
    image: "assets/nike_flex.png",
    description: "Blue and silver Nike Flex Control II trainer shoes.",
    sizes: [8, 9, 10],
    inStock: false
  },
  {
    id: 119,
    title: "Campus Oxyfit Mesh Running Shoes",
    category: "sports",
    categoryLabel: "Sports & Sneakers",
    brand: "Campus",
    price: 1899,
    oldPrice: 2299,
    rating: 4.7,
    reviewsCount: 110,
    badge: "Archived Item",
    image: "assets/campus_oxyfit.png",
    description: "Campus Oxyfit running sneakers with responsive Phylon sole.",
    sizes: [6, 7, 8, 9, 10],
    inStock: false
  },
  {
    id: 120,
    title: "Paragon Waterproof Floater Outdoor Sandals",
    category: "sports",
    categoryLabel: "Floaters & Slippers",
    brand: "Paragon",
    price: 649,
    oldPrice: 799,
    rating: 4.7,
    reviewsCount: 160,
    badge: "Archived Item",
    image: "assets/woodland_boot.png",
    description: "Durable all-weather Paragon floaters with multi-strap adjustability.",
    sizes: [6, 7, 8, 9, 10],
    inStock: false
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = ARCHIVED_PRODUCTS;
}
